config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end

  delete 'doses/:id', to: 'doses#destroy', as: 'dose'
  root 'cocktails#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
  belongs_to :ingredient
  belongs_to :cocktail, dependent: :destroy
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(allowed_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def update

  end

  def destroy
     @cocktail = Cocktail.find(params[:id])
     @cocktail.destroy
     redirect_to cocktails_path
  end

  private

  def allowed_params
    params.require(:cocktail).permit(:name, :ingredient, :dose, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @ingredients = Ingredient.all
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(allowed_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @ingredients = Ingredient.all
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
    redirect_to cocktails_path
  end

  private

  def allowed_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :ingredient %>
  <%= f.input :dose%>
  <%= f.submit "add a cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/delete.html.erb
<h1>Cocktails#delete</h1>
<p>Find me in app/views/cocktails/delete.html.erb</p>

app/views/cocktails/index.html.erb
  <h1>Cocktails list</h1>
<% @cocktails.each do |c| %>
<%= link_to c.name, cocktail_path(c) %><br>
<% end %>
<%= link_to 'Create new cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>Create your new cocktail</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add a cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<%= @cocktail.name %><br>
<% @cocktail.doses.each do |d| %>
<%= d.description %><br>
<%= d.ingredient.name %><br>
<%= link_to 'Delete', dose_path(d), method: :delete %>
<% end %>
<%= link_to 'Create dose', new_cocktail_dose_path(@cocktail) %>
<%= link_to 'Back to Index', cocktails_path %><br>
<%= link_to 'Delete Cocktail', cocktail_path(@cocktail), method: :delete %>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/delete.html.erb
<h1>Doses#delete</h1>
<p>Find me in app/views/doses/delete.html.erb</p>

app/views/doses/new.html.erb
<h1>Add the dose</h1>

<%= simple_form_for [ @cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, as: :select, collection: @ingredients %>
  <%= f.input :cocktail_id, as: :hidden, input_html: { value: @cocktail.id }  %>
  <%= f.submit "add dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>